server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://125.88.213.38:3306/blogdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: chy010731
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chyuan.blog.model
